paths:
  raw_data: data/raw/accidents.csv
  processed_data: data/processed/accidents_clean.csv
  model_dir: model
split:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
target: severity
model:
  type: RandomForestClassifier
  params:
    n_estimators: 200
    random_state: 42
